services:
  common-network-service:
    networks:
      - common-network
  microservice-base-config:
    extends:
      service: common-network-service
    deploy:
      resources:
        limits:
          memory: 700m


  microservice-configurationserver-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:8071


  microservice-eureka-config:
    extends:
      service: microservice-configurationserver-config
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/




