global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'administration_job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'administration:8080' ]
  - job_name: 'evaluation_job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'evaluation:8081' ]
  - job_name: 'configserver_job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'configserver:8071' ]
  - job_name: 'apigateway_job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'apigateway:8072' ]
  - job_name: 'eurekaserver_job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eurekaserver:8070' ]

